@extends('sistema_cobros.layouts.formularios')
@section("content")
    <x-page-breadcrumb :titulo="$titulo_breadcrumb" :subtitulo="$subtitulo_breadcrumb" />

    @if(isset($view))

        @switch($view)
         {{-- Asociado a Models\ListadoFormularios --}}
            @case("sistema_cobros.formularios.escuelas")
                @include($view,["titulo_formulario"=>$titulo_formulario,"route"=>((isset($routeStore)?$routeStore:$routeUpdate)),"accion"=>$accion,"obj"=>((isset($escuela)?$escuela:""))])
                @break
            @case("sistema_cobros.formularios.sistemas_academicos")
                @include($view,["titulo_formulario"=>$titulo_formulario,
                                "route"=>((isset($routeStore)?$routeStore:$routeUpdate)),
                                "accion"=>$accion,
                                "obj"=>((isset($sistema)?$sistema:"")),
                                "escuelas"=>((isset($escuelas)?$escuelas:"")),
                                "niveles"=>((isset($nivelesDropdown)?$nivelesDropdown:""))])
                @break
            @case("sistema_cobros.formularios.alumnos")
                @include($view,["titulo_formulario"=>$titulo_formulario,
                                "route"=>((isset($routeStore)?$routeStore:$routeUpdate)),
                                "accion"=>$accion,
                                "obj"=>((isset($alumno)?$alumno:"")),
                                "sistemas"=>((isset($sistemas)?$sistemas:""))])
                @break
            @case("sistema_cobros.formularios.conceptos_cobros")
                @include($view,["titulo_formulario"=>$titulo_formulario,
                                "route"=>((isset($routeStore)?$routeStore:$routeUpdate)),
                                "accion"=>$accion,
                                "obj"=>((isset($concepto)?$concepto:"")),
                                "escuelas"=>((isset($escuelas)?$escuelas:""))])
                @break
            @case("sistema_cobros.formularios.costos_conceptos")
                @include($view,["idSelect2"=>$idSelect2,
                                "titulo_formulario"=>$titulo_formulario,
                                "route"=>((isset($routeStore)?$routeStore:$routeUpdate)),
                                "accion"=>$accion,
                                "obj"=>((isset($costo)?$costo:"")),
                                "sistemas"=>((isset($sistemas)?$sistemas:""))])
                @break
            @case("sistema_cobros.formularios.cuentas")
                @include($view,["idSelect2"=>$idSelect2,"titulo_formulario"=>$titulo_formulario,"route"=>$routeStore,"accion"=>$accion,"formulario"=>$formulario])
                @break
            @case("sistema_cobros.formularios.enlace_cuenta_alumno")
                @include($view,["alumno"=>$alumno,
                            "titulo_formulario"=>$titulo_formulario,
                            "route"=>$routeStore,
                            "accion"=>$accion,
                            "formulario"=>$formulario])
                @break
            @case("sistema_cobros.formularios.cobros")
                @include($view,["idSelect2"=>$idSelect2,
                "idSelect2_2"=>$idSelect2_2,
                "estadosCobro"=>$estadosCobro,
                "titulo_formulario"=>$titulo_formulario,
                "route"=>$routeStore,
                "accion"=>$accion,
                "formulario"=>$formulario])
                @break
            @case("sistema_cobros.formularios.roles")
                @include($view,[
                "titulo_formulario"=>$titulo_formulario,
                "route"=>$routeStore,
                "accion"=>$accion,
                "formulario"=>$formulario])
                @break
            @case("sistema_cobros.formularios.permisos")
                @include($view,[
                "titulo_formulario"=>$titulo_formulario,
                "route"=>$routeStore,
                "accion"=>$accion,
                "formulario"=>$formulario])
                @break
            @case("sistema_cobros.formularios.rol_permisos")
                @include($view,[
                "titulo_formulario"=>$titulo_formulario,
                "route"=>$routeStore,
                "accion"=>$accion,
                "formulario"=>$formulario])
                @break
            @case("sistema_cobros.formularios.usuarios")
                @include($view,[
                "roles"=>$roles,
                "titulo_formulario"=>$titulo_formulario,
                "route"=>$routeStore,
                "accion"=>$accion,
                "formulario"=>$formulario])
                @break
            @case("sistema_cobros.formularios.categoria_cobros")
                @include($view,[
                    "titulo_formulario"=>$titulo_formulario,
                    "route"=>((isset($routeStore)?$routeStore:$routeUpdate)),
                    "accion"=>$accion,
                    "obj"=>((isset($categoria)?$categoria:"")),
                    "sistemas"=>((isset($sistemas)?$sistemas:""))])
            @break
            @case("sistema_cobros.formularios.promociones")
                @include($view,[
                    "titulo_formulario"=>$titulo_formulario,
                    "route"=>((isset($routeStore)?$routeStore:$routeUpdate)),
                    "accion"=>$accion,
                    "promocion"=>((isset($promocion)?$promocion:""))]);
            @break
            @default
        @endswitch
        
    @endif
    
@endsection