@if(isset($tipo))
    @switch($tipo)
        @case("tabla")
            @include('components.informes.tabla_config',["index"=>$index,"valor_col"=>$col,'id'=>$id])
        @break
        @case("tarjeta")
            @include('components.informes.tarjeta_config',["index"=>$index,"valor_col"=>$col,'id'=>$id])
        @break
        @case("texto_sm")
            @include('components.informes.texto_config',["index"=>$index,"valor_col"=>$col,'id'=>$id])
        @break
        @case("texto_md")
            @include('components.informes.texto_config',["index"=>$index,"valor_col"=>$col,'id'=>$id])
        @break
        @case("texto_lg")
            @include('components.informes.texto_config',["index"=>$index,"valor_col"=>$col,'id'=>$id])
        @break
        @case("grafica")
            @include('components.informes.grafica_config',["index"=>$index,"valor_col"=>$col,'id'=>$id])
        @break
        @case("espacio")
            @include('components.informes.espacio',["index"=>$index,"valor_col"=>$col,'id'=>$id])
        @break
    
        @default
    @endswitch
@endif